Add html/css javascript
Mike47ip/JavascriptCapstone pull request #1
Opened 2023-07-05 18:48 UTC by Mike47ip

Whole section of the website is created from the header to the footer. Javascript is then used to render the Featured Speakers sections dynamically. A new page is created for the About section of the website as well.

2023-07-07 12:40 UTC, aamirkhan2478 requested changes
Hi @Mike47ip, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
- [x] Please add only one `h1` tag for other headings you should use `h2`, `h3`, `h4`, `h5` or `h6` tags because this is good for semantical so kindly replace all `h1` tags with other `hx` tags :slightly_smiling_face:

2023-07-07 12:40 UTC, aamirkhan2478 commented on css_folder/style.css
- [x] Please stick to the Behance design as much as possible but you didn't follow the color and font-family is not same as Behance design so kindly add same colour and font-family


![Screenshot from 2023-07-07 15-53-58](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/474b149f-c20e-48d8-95aa-9cbd374bbb9c)

![Screenshot from 2023-07-07 15-54-04](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/20453be7-3d03-4ca6-8d35-82ab0dfd1773)

**_Note: `Cocogoose` is a paid font-family so you just use `Lato` font-family_**

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +          <li>My Page</li>
- [x] Well done :clap: your design is very good :+1: but there are some spacing issues in your top and bottom navbar so kindly fix it :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

_**Fix these issues on both pages**_
**Your Design**
![Screenshot from 2023-07-07 15-29-31](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/107a1ce9-3065-4b5e-9614-43fb718aa4de)
 
**Behance Design**
![Screenshot from 2023-07-07 15-47-45](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/f0f9cc87-b155-4c91-8acf-7fd298070fbb)


- [x] If you check your design the top and bottom navbar alignment is not well so kindly fix alignment as well :+1:

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +        </div>
## Desktop Version

- [x] As I mentioned above :point_up_2: please stick to the Behance design as much as possible but your hero section is not the same as the Behance design there are lots of spacing and alignment issues and also font size and font family are not the same as Behance design :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-39-03](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/a42901a6-6357-4a66-a5cb-4bd2f33bf2c9)

**Behance Design**
![Screenshot from 2023-07-07 15-48-01](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/50abe43b-2c59-4984-a70a-a72ae861430b)

- [x] If you check Behance's design there are some blur effects but in your case, there are no blur effects so kindly add blur effects as well :+1:


## Mobile Version

- [x] As I mentioned above :point_up_2: please stick to the Behance design but your background image does not look professional because the text is not shown well so kindly replace your background image with a good background image also please fix all your alignment and spacing and also font size and font family issues as well :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 16-00-39](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/73c5ed53-2547-40ed-9568-a53d42242286)

**Behance Design**
![Screenshot from 2023-07-07 16-00-24](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/590ee16a-2377-4d5d-a51e-ba82289c02eb)

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +              </ul>
## Desktop Version

- [x] As I mentioned above :point_up_2: please stick to the Behance design if you check the Behance design there are some hover effects to a card but in your case, you didn't add any hover effect to the cards so kindly fix this issue as well :+1: check below :point_down:  the comparison between your design and Behacne design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-39-15](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/7bb7b2c3-1f45-4229-85a9-6c0a4482c5e4)

**Behance Design**
![Screenshot from 2023-07-07 15-48-13](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/868eaaad-e8ad-48f1-9a0b-577d5fb80cc1)


## Mobile Version

- [x] As I mentioned above :point_up_2: please stick to the Behance design the icons are missing from your all cards so kindly add icons as well :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face:

**Your Design**
![Screenshot from 2023-07-07 16-01-13](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/859ece61-8405-4c6e-9db7-70a881f096d4)

**Behance Design** 
![Screenshot from 2023-07-07 16-01-27](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/f628139b-1b3f-40d3-bb14-f80189a9c566)

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +              <a class="butt" href="#">Click Here To Register!</a>
- [ ] As I mentioned above :point_up_2: please stick to the Behance design but your `a` tag design is not the same as Behance Design so kindly fix your design as well :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face:

**Your Design**
![Screenshot from 2023-07-07 15-39-27](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/9f06e640-0622-4211-a0da-654721ce547c)

**Behance Design**  
![Screenshot from 2023-07-07 15-48-24](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/38168471-a0d3-4081-b93e-fb1b0d9445f6)

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +            </div>
-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but there are some spacing and font-size problems so kindly fix these issues as well :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-48-55](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/40965aac-a833-4f9b-8416-f5ed204d8ab0)

**Behance Design**
![Screenshot from 2023-07-07 15-48-32](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/57f38590-fd78-4f5b-869b-ea6dbf09cb4e)

2023-07-07 12:40 UTC, aamirkhan2478 commented on index.html
> +            <div class="featureContainer">
- [ ] As I mentioned above :point_up_2: please stick to the Behance design but if You check your Featured Speakers heading icon is not the same as Behance Design so kindly use the same icon mentioned in Behance Design :+1:  check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-49-15](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/0e36c2d7-7c92-4779-91db-b7e4824cd509)

**Behance Design**
![Screenshot from 2023-07-07 15-49-09](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/9adc9c0e-128f-4d1d-bb76-7130d7be4695)

2023-07-07 12:40 UTC, aamirkhan2478 commented on new_tab/about.html
> +            really be glad to assist you! <br />
## Desktop Version

-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but the heading is missing and also the background image is missing and also the spacing and alignments issues are there and also font size and font family are not the same as the Behance design so kindly fix these all issues :+1:  check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-58-36](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/f6f1d2b9-cd78-4528-9ff5-bdf5947e10fd)

**Behance Design**
![Screenshot from 2023-07-07 15-58-20](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/6294bedd-e470-4e57-a917-45e788c78c3d)

## Mobile Version

-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but the background image is missing and also the heading is not match with Behance design and also the font size and font family is not matching with Behance design  so kindly fix all these issues as well :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 16-02-03](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/d059c410-bb29-40d9-b6bf-41b65efdfb97)

**Behance Design**
![Screenshot from 2023-07-07 16-02-42](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/275ce13a-96b9-4516-bca3-1b206ca85d54)

- [ ] Also, if you check your design there are some spacing and alignment issues so kindly fix this issue as well :+1:

2023-07-07 12:40 UTC, aamirkhan2478 commented on new_tab/about.html
> +
## Desktop Version

-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but there are some spacing and alignments issues and also font size and font family are not the same as the Behance design so kindly fix all these issues :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-59-03](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/7f1b1c0d-7ad5-4fee-ae40-995a51e6a569)

**Behance Design**
![Screenshot from 2023-07-07 15-58-52](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/84ce9bb6-b0cc-4749-9d01-2ca3cf95b524)

## Mobile Version

-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but there are some spacing and alignments issues and also font size and font family are not the same as the Behance design so kindly fix all these issues :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 16-03-08](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/4e3f0b42-a922-4126-acd1-5cfd066eb4df)

**Behance Design**
![Screenshot from 2023-07-07 16-03-22](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/2cf58bb6-9d50-42e0-ab91-c8c181145c70)

2023-07-07 12:40 UTC, aamirkhan2478 commented on new_tab/about.html
> +    </footer>
-  [ ] As I mentioned above :point_up_2: please stick to the Behance design but the background color of your footer is not the same as the Behance design so kindly as the correct background color which is match with Behance design :+1: check below :point_down:  the comparison between your design and Behance design :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-07-07 15-59-16](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/61780e98-f69c-46f4-bd83-7f1b43a328a2)

**Behance Design**
![Screenshot from 2023-07-07 15-59-30](https://github.com/Mike47ip/JavascriptCapstone/assets/45226848/fb629aa5-4321-4e98-b236-8bce1ebb914e)

2023-07-07 13:07 UTC, Mike47ip commented
Why so many changes man??. We were told to personalize the website to make
it unique and different from the original not copy and paste everything we
see. This ridiculous. It is just too much unnecessary changes you requiring


On Fri, 7 Jul 2023 at 12:40, Aamir khan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Mike47ip <https://github.com/Mike47ip>,
>
>
> <https://camo.githubusercontent.com/f1e592d311095c9033da741c6114377c2c46ac8f209ed4783466db1ddf8856cd/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f52635a6c58566d6c386f4b746f47516571652f67697068792e6769663f6369643d6563663035653437637735706a6431676170647a6b3174337670306e37336361756a6f71787733766b63753873736e67267269643d67697068792e6769662663743d67>
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't been addressed yet.
> Highlights
>
> ✔️ Good Effort
> ✔️ Your design is good.
> ✔️ All linter passed
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you take them into account as they can
> make your code better. Some of them were missed by the previous reviewer
> and addressing them will really improve your application.*
>
> Cheers, and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Remember to tag me in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> On index.html
> <https://github.com/Mike47ip/JavascriptCapstone/pull/1#discussion_r1255622789>
> :
>
>    - Please add only one h1 tag for other headings you should use h2, h3,
>    h4, h5 or h6 tags because this is good for semantical so kindly
>    replace all h1 tags with other hx tags 🙂
>
> ------------------------------
>
> On css_folder/style.css
> <https://github.com/Mike47ip/JavascriptCapstone/pull/1#discussion_r1255647545>
> :
>
>    - Please stick to the Behance design as much as possible but you
>    didn't follow the color and font-family is not same as Behance design so
>    kindly add same colour and font-family
>
> [image: Screenshot from 2023-07-07 15-53-58]
> <https://user-images.githubusercontent.com/45226848/251721528-474b149f-c20e-48d8-95aa-9cbd374bbb9c.png>
>
> [image: Screenshot from 2023-07-07 15-54-04]
> <https://user-images.githubusercontent.com/45226848/251721579-20453be7-3d03-4ca6-8d35-82ab0dfd1773.png>
>
> *Note: Cocogoose is a paid font-family so you just use Lato font-family*
> ------------------------------
>
> In index.html
> <https://github.com/Mike47ip/JavascriptCapstone/pull/1#discussion_r1255668205>
> :
>
> > +      <nav class="header">
> +        <div class="navbarMobile">
> +          <ul class="menumo">
> +            <li class="grid">
> +              <a href="#"><ion-icon name="grid"></ion-icon></a>
> +            </li>
> +            <li class="menu-nth"></li>
> +            <li class="subscribe">Subscribe</li>
> +          </ul>
> +        </div>
> +      </nav>
> +
> +      <nav class="header1">
> +        <ul>
> +          <li><ion-icon name="logo-facebook"></ion-icon></li>
> +          <li><ion-icon name="logo-twitter"></ion-icon></li>
> +          <li>English</li>
> +          <li>My Page</li>
>
>
>    - Well done 👏 your design is very good 👍 but there are some spacing
>    issues in your top and bottom navbar so kindly fix it 👍 check below 👇
>    the comparison between your design and Behance design 🙂
>
> *Fix these issues on both pages*
> *Your Design*
> [image: Screenshot from 2023-07-07 15-29-31]
> <https://user-images.githubusercontent.com/45226848/251725031-107a1ce9-3065-4b5e-9614-43fb718aa4de.png>
>
> *Behance Design*
> [image: Screenshot from 2023-07-07 15-47-45]
> <https://user-images.githubusercontent.com/45226848/251725064-f0f9cc87-b155-4c91-8acf-7fd298070fbb.png>
>
>    - If you check your design the top and bottom navbar alignment is not
>    well so kindly fix alignment as well 👍
>
> ------------------------------
>
> In index.html
> <https://github.com/Mike47ip/JavascriptCapstone/pull/1#discussion_r1255701885>
> :
>
> > +      <section>
> +        <div id="homepage" class="homepage">
> +          <p>"Hello World"</p>
> +          <h1>GLOBAL LEADERS' <br />CONFERENCE</h1>
> +          <div class="Statement">
> +            You are all warmly welcome yet another beautiful event being host at
> +            the four corners of the globe. An international festering of talents
> +            and skills.
> +          </div>
> +          <div class="homedate">2018.12.08(fri)_18(wed)</div>
> +          <div ***@***.*** of State Building,USA</div>
> +        </div>
>
> Desktop Version
>
>    - As I mentioned above 👆 please stick to the Behance design as much
>    as possible but your hero section is not the same as the Behance design
>    there are lots of spacing and alignment issues and also font size and font
>    family are not the same as Behance design 👍 check below 👇 the
>    comparison between your design and Behance design 🙂
>
> *Your Design*
> [image: Screenshot from 2023-07-07 15-39-03]
> <https://user-images.githubusercontent.com/45226848/251731034-a42901a6-6357-4a66-a5cb-4bd2f33bf2c9.png>
>
> *Behance Design*
> [image: Screenshot from 2023-07-07 15-48-01]
> <https://user-images.githubusercontent.com/45226848/251730990-50abe43b-2c59-4984-a70a-a72ae861430b.png>
>
>    - If you check Behance's design there are some blur effects but in
>    your case, there are no blur effects so kindly add blur effects as well
>    👍
>
> Mobile Version
>
>    - As I mentioned above 👆 please stick to the Behance design but your
>    background image does not look professional because the text is not shown
>    well so kindly replace your background image with a good background image
>    also please fix all your alignment and spacing and also font size and font
>    family issues as well 👍 check below 👇 the comparison between your
>    design and Behance design 🙂
>
> *Your Design*
> [image: Screenshot from 2023-07-07 16-00-39]
> <https://user-images.githubusercontent.com/45226848/251740310-73c5ed53-2547-40ed-9568-a53d42242286.png>
>
> *Behance Design*
> [image: Screenshot from 2023-07-07 16-00-24]
> <https://user-images.githubusercontent.com/45226848/251740121-590ee16a-2377-4d5d-a51e-ba82289c02eb.png>
> ------------------------------
>
> In index.html
> <https://github.com/Mike47ip/JavascriptCapstone/pull/1#discussion_r1255709571>
> :
>
> > +          <div id="programContainer" class="programContainer">
> +            <h1>MAIN PROGRAM</h1>
> +            <div class="aboutContainer">
> +              <ul class="Program">
> +                <li id="icon"><ion-icon name="school-outline"></ion-icon></li>
> +                <li class="text" id="text">Lecture</li>
> +                <li id="passage">
> +                  Pay keen attention to whatever is being taught in the lecture
> +                  room
> +                </li>
> +              </ul>
> +              <ul class="Program">
> +                <li id="icon"><ion-icon name="eye-outline"></ion-icon></li>
> +                <li class="text" id="text">CC Exhibition</li>
> +                <li id="passage">
> +                  Lorem ipsum dolor sit  [...]

2023-07-07 22:11 UTC, Mike47ip commented
The changes previous previewer required were enormous. It was like I had to redo the whole project in such short notice. I was only trying to make create a unique personalized portfolio for my resume. Please consider before you pass your next verdict on these codes. Thank you

2023-07-07 22:59 UTC, tufoinnkuo10 requested changes
Hi @Mike47ip 

great job so far. There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ design well followed

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-07-07 22:59 UTC, tufoinnkuo10 commented on new_tab/about.html
> +     2023 Global Leaders Conference <br />
- [ ] The background color of the mobile about footer page has a white color.
- [optional] you are missing the partner section in the mobile about page. please kindly add that so as to align with the design.
yours
 
![Screenshot (1227)](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/6a779fb6-b06b-44af-a3d5-b48bb6806faa)
original
![Screenshot (1168)](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/8b54804f-9938-4e0f-875b-c76efca66064)

2023-07-07 22:59 UTC, tufoinnkuo10 commented on new_tab/about.html
> +     <ul>
- [ ] please, like the previous reviewer noted, kindly change the background of the mobile headline section. Please use a clearer background. Remember, the design should look alike, and only the contents should be personalized.below you can see how different it looks from the original design
yours
![Screenshot (1225)](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/17a27bd9-372b-4333-9e79-a6262e9693b8)
original
![Screenshot (1034)](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/568d692c-a6b5-4904-a230-c3c13457c247)

2023-07-07 22:59 UTC, tufoinnkuo10 commented on index.html
> +      <button id="register" class="Join">
- [ ] please as informed by previous reviewer, under the cards is an underlined text in the desktop version not a button like in your case.
- [optional] the cards have their heading in red. You use a yellow color. Please always respect guidelines and details. 
yours
![Screenshot (1226)_LI](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/55785155-7d08-4880-9fd8-5f72aa65798d)
original
![Screenshot (1167)](https://github.com/Mike47ip/JavascriptCapstone/assets/65298048/969928f6-5854-41c4-af05-e397c6e28a06)

2023-07-08 15:11 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Mike47ip , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
|  <img src="https://media4.giphy.com/media/n5O7Vfcz2WYk4lU0cI/giphy.gif"/> |

### Highlights
✅ ... Green linters
✅ ... Great design, Great readme

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 15:56 UTC, merged